blueprints/administrator_blueprint.py
from flask import Blueprint, request
from controller.manager import manager_trainee_controller, manager_controller, manager_advisor_controller, manager_programs_controller

manager_blueprint = Blueprint("manager", __name__)


@manager_blueprint.route('/manager', methods=["GET"])
def dashboard_view():
    return manager_controller.index(request)


# Manager-pationt Routes
@manager_blueprint.route('/pationt/pending', methods=["GET"])
def get_pending_pationt_view():
    return manager_pationt_controller.get_pending_pationt(request)


@manager_blueprint.route('/approve/pationt/', methods=["POST"])
def approve_pationt():
    return manager_pationt_controller.approve_pationt_registration(request)


@manager_blueprint.route('/reject/pationt/', methods=["POST"])
def reject_pationt():
    return manager_pationt_controller.reject_pationt_registration(request)


@manager_blueprint.route('/tpationt/requests', methods=["GET"])
def get_pationt_requests():
    return manager_pationt_controller.get_pationt_requests_view(request)


@manager_blueprint.route('/pationt/requests/approve', methods=["POST"])
def approve_pationt_requests():
    return manager_pationt_controller.approve_pationt_request(request)


@manager_blueprint.route('/tpationt/requests/reject', methods=["POST"])
def reject_pationt_requests():
    return manager_pationt_controller.reject_pationt_request(request)


@manager_blueprint.route('/pationt/deactivate/all', methods=["GET"])
def get_deactivate_pationt_view():
    return manager_pationt_controller.get_deactivate_pationt(request)


@manager_blueprint.route('/pationt/deactivate', methods=["POST"])
def deactivate_pationt():
    return manager_pationt_controller.approve_pationt_deactivation(request)


@manager_blueprint.route('/pationt/reject/deactivate', methods=["POST"])
def reject_deactivate_pationt():
    return manager_pationt_controller.reject_pationt_deactivation(request)


@manager_blueprint.route('/pationt/account', methods=["GET"])
def get_pationt_accounts_view():
    return manager_pationt_controller.get_pationt_account(request)


@manager_blueprint.route('/pationt/account/details', methods=["GET"])
def get_pationt_accounts_details_view():
    return manager_pationt_controller.get_pationt_account_details(request)


@manager_blueprint.route('/pationt/approve/modifications', methods=["POST"])
def accept_pationt_modification():
    return manager_pationt_controller.accept_pationt_modifications(request)


@manager_blueprint.route('/pationt/reject/modifications', methods=["POST"])
def reject_pationt_modification():
    return manager_pationt_controller.reject_pationt_modifications(request)


# Manager-dector Routes


@manager_blueprint.route('/dector/pending', methods=["GET"])
def get_pending_dector_view():
    return manager_dector_controller.get_pending_dector(request)


@manager_blueprint.route('/approve/dector', methods=["POST"])
def approve_dector():
    return manager_dector_controller.approve_dectors_registration(request)


@manager_blueprint.route('/reject/dector', methods=["POST"])
def reject_dector():
    return manager_dector_controller.reject_dectors_registration(request)


@manager_blueprint.route('/dectors/account', methods=["GET"])
def get_dectors_accounts_view():
    return manager_dector_controller.get_dector_account(request)


@manager_blueprint.route('/dectors/account/details', methods=["GET"])
def get_dectors_accounts_details_view():
    return manager_dector_controller.get_dector_account_details(request)


@manager_blueprint.route('/dectors/approve/modifications', methods=["POST"])
def accept_dector_modification():
    return manager_dector_controller.accept_dector_modifications(request)


@manager_blueprint.route('/dectors/account/details', methods=["POST"])
def reject_dector_modification():
    return manager_dector_controller.reject_dector_modifications(request)


@manager_blueprint.route('/dectors/deactivate/all', methods=["GET"])
def get_deactivate_dectors_view():
    return manager_dector_controller.get_deactivate_dectors(request)


@manager_blueprint.route('/dector/deactivate', methods=["POST"])
def deactivate_dector():
    return manager_dector_controller.approve_dector_deactivation(request)


@manager_blueprint.route('/dector/reject/deactivate', methods=["POST"])
def reject_deactivate_dector():
    return manager_dector_controller.reject_dector_deactivation(request)

# Progam Routes

@manager_blueprint.route('/programs', methods=["GET"])
def get_all_programs_view():
    return manager_programs_controller.get_all_programs(request)


@manager_blueprint.route('/programs/create/form', methods=["GET"])
def get_add_program_view():
    return manager_programs_controller.get_add_program(request)


@manager_blueprint.route('/program/create', methods=["POST"])
def add_program():
    return manager_programs_controller.handle_add_program(request)


@manager_blueprint.route('/programs/edit', methods=["GET"])
def get_edit_program_view():
    return manager_programs_controller.get_edit_program(request)


@manager_blueprint.route('/programs/edit/save', methods=["POST"])
def edit_program():
    return manager_programs_controller.handle_edit_program(request)


@manager_blueprint.route('/program/delete', methods=["POST"])
def delete_program():
    return manager_programs_controller.handle_delete_program(request)

# Manager - Billing
@manager_blueprint.route('/billing', methods=["GET"])
def get_balance_sheet_view():
    return manager_controller.get_balance_sheet(request)



# Manager - Emailing
@manager_blueprint.route('/email/create', methods=["GET"])
def get_email_form():
    return manager_controller.get_email_form(request)


@manager_blueprint.route('/email/send', methods=["POST"])
def send_email():
    return manager_controller.send_email(request)



# Manager - System Log
@manager_blueprint.route('/systemlog', methods=["GET"])
def get_system_log():
    return manager_controller.get_system_log(request)

templates/manager/billing.html
{% extends "layouts/manager_base.html" %}

{% block title %} Balance Sheet {% endblock %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Manager</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Manager</a></li>
                    <li class="breadcrumb-item"><a href="#">Balance Sheet</a></li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <!-- Table with stripped rows -->
                            <table class="table datatable">
                                <thead>
                                <tr>
                                    <th scope="col">Transaction ID</th>
                                    <th scope="col">User ID</th>
                                    <th scope="col">Transaction Type</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">Transaction Time</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for transaction in transactions %}
                                    <tr>
                                        <th scope="row">{{ transaction[0] }}</th>
                                        <td>{{ transaction[1] }}</td>
                                        <td>{{ transaction[2] }}</td>
                                        <td>{{ transaction[3] }}</td>
                                        <td>{{ transaction[4] }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <div class="modal fade" id="verticalycentered" tabindex="-1">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Vertically Centered</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            Non omnis incidunt qui sed occaecati magni asperiores est mollitia. Soluta
                                            at et reprehenderit. Placeat autem numquam et fuga numquam. Tempora in
                                            facere consequatur sit dolor ipsum. Consequatur nemo amet incidunt est
                                            facilis. Dolorem neque recusandae quo sit molestias sint dignissimos.
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                                Close
                                            </button>
                                            <button type="button" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- End Vertically centered Modal-->

                        </div>
                    </div>
                </div>
            </div>

        </section>

    </main><!-- End #main -->
{% endblock %}



templates/manager/index.html
{% extends "layouts/manager_base.html" %}

{% block title %} Manager Dashboard {% endblock %}
{% block content %}
    <!-- Manager Dashboard contents goes here, feel free to add whatever you want -->
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Manager</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                </ol>
            </nav>
        </div><!-- End Page Title -->
        <section class="section profile">
            <div class="row">
              <div class="col-xl-4">      
                <div class="card">
                  <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                    <h2>{{ manager.username }}</h2>
                    <h3>{{ manager.email }}</h3>
                    <div class="social-links mt-2">
                      <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                  </div>
                </div>
      
              </div>
      
              <div class="col-xl-8">
      
                <div class="card">
                  <div class="card-body pt-3">
                    <!-- Bordered Tabs -->
                    <ul class="nav nav-tabs nav-tabs-bordered">
      
                      <li class="nav-item">
                        <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                      </li>
      
                      
                    </ul>
                    <div class="tab-content pt-2">
      
                      <div class="tab-pane fade show active profile-overview" id="profile-overview">
                        <h5 class="card-title">About</h5>
                        <p class="small fst-italic">{{manager.fullname}} is responsible for managing the system, trainees, and advisors. 
                            {{manager.fullname}} can review training requests, manage all registered trainees and advisors accounts.  </p>
      
                        <h5 class="card-title">Profile Details</h5>
      
                        <div class="row">
                          <div class="col-lg-3 col-md-4 label ">Full Name</div>
                          <div class="col-lg-9 col-md-8">{{ manager.fullname}}</div>
                        </div>
      
                        <div class="row">
                          <div class="col-lg-3 col-md-4 label">Email</div>
                          <div class="col-lg-9 col-md-8">{{ manager.email}}</div>
                        </div>
      
                      </div>
      
                      <div class="tab-pane fade profile-edit pt-3" id="profile-edit">
      
                        <!-- Profile Edit Form -->
                        <form>
                          <div class="row mb-3">
                            <!-- <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label> -->
                            <div class="col-md-8 col-lg-9">
                              <!-- <img src="{{ manager.img }}" alt="Profile">
                              <div class="pt-2">
                                <a href="#" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-upload"></i></a>
                                <a href="#" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>
                              </div> -->
                            </div>
                          </div>
      
                          <div class="row mb-3">
                            <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Full Name</label>
                            <div class="col-md-8 col-lg-9">
                              <input name="fullName" type="text" class="form-control" id="fullName" value="{{manager.username}}">
                            </div>
                          </div>     
                          
                          <div class="row mb-3">
                            <label for="department" class="col-md-4 col-lg-3 col-form-label">Department</label>
                            <div class="col-md-8 col-lg-9">
                              <input name="department" type="text" class="form-control" id="department" value="{{manager.department}}">
                            </div>
                          </div>
            
                          <div class="row mb-3">
                            <label for="Email" class="col-md-4 col-lg-3 col-form-label">Email</label>
                            <div class="col-md-8 col-lg-9">
                              <input name="email" type="email" class="form-control" id="Email" value="{{manager.email}}">
                            </div>
                          </div>
      
                          <div class="row mb-3">
                            <label for="Linkedin" class="col-md-4 col-lg-3 col-form-label">Linkedin Profile</label>
                            <div class="col-md-8 col-lg-9">
                              <input name="linkedin" type="text" class="form-control" id="Linkedin" value="https://linkedin.com/#">
                            </div>
                          </div>
      
                          <div class="text-center">
                            <button type="submit" class="btn btn-primary">Save Changes</button>
                          </div>
                        </form>
      
                      </div>
      
                      <div class="tab-pane fade pt-3" id="profile-settings">                 
                      </div>
                    </div><!-- End Bordered Tabs -->
      
                  </div>
                </div>
      
              </div>
            </div>
          </section>

    </main><!-- End #main -->
{% endblock %}

templates/manager/logging.html
{% extends "layouts/manager_base.html" %}

{% block title %} Logging {% endblock %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Manager</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Manager</a></li>
                    <li class="breadcrumb-item"><a href="#">Logging Details</a></li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <!-- Table with stripped rows -->
                            <table class="table datatable">
                                <thead>
                                <tr>
                                    <th scope="col">logging ID</th>
                                    <th scope="col">User ID</th>
                                    <th scope="col">logging Type</th>
                                    <th scope="col">Amount</th>
                                    <th scope="col">logging Time</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for logging in loggings %}
                                    <tr>
                                        <th scope="row">{{ logging[0] }}</th>
                                        <td>{{ logginh[1] }}</td>
                                        <td>{{ logging[2] }}</td>
                                        <td>{{ logging[3] }}</td>
                                        <td>{{ logging[4] }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                           
                        </div>
                    </div>
                </div>
            </div>

        </section>

    </main><!-- End #main -->
{% endblock %}

templates/manager/mailing.html
{% extends "layouts/manager_base.html" %}

{% block title %} Mailing {% endblock %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Send an Email</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Manager</a></li>
                    <li class="breadcrumb-item"><a href="">Send an Email</a></li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    {% with messages = get_flashed_messages(with_categories=True) %}
                        {% if messages %}
                            <ul class="flash-messages">
                            {% for category, message in messages %} 
                                {% if category == 'error' %}
                                <div class="alert alert-danger bg-danger text-light border-0 alert-dismissible fade show" role="alert">
                                    {{message}}
                                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                                {% elif category == 'success' %}
                                <div class="alert alert-success bg-success text-light border-0 alert-dismissible fade show" role="alert">
                                    {{message}}
                                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                                {% endif %}
                            {% endfor %}
                            </ul>                                        
                        {% endif %}
                    {% endwith %}
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Email Details</h5>
                            <form action="{{url_for('manager.send_email')}} " method="post">
                                <div class="row gy-4">
                
                                  <div class="col-md-12 ">
                                    <input type="email" class="form-control" name="recipient" placeholder="Recipient Email" required>
                                  </div>
                  
                                  <div class="col-md-12">
                                    <input type="text" class="form-control" name="subject" placeholder="Subject" required>
                                  </div>
                  
                                  <div class="col-md-12">
                                    <textarea class="form-control" name="message" rows="6" placeholder="Message" required></textarea>
                                  </div>
                  
                                  <div class="col-md-12 text-center">   
                                    <button type="submit" class="btn btn-primary">Send</button>
                                  </div>
                  
                                </div>
                              </form>
                        </div>
                    </div>
                </div>
            </div>

        </section>

    </main><!-- End #main -->
{% endblock %}