blueprints/administrator_blueprint.py
from flask import Blueprint, request
from controller.manager import manager_trainee_controller, manager_controller, manager_advisor_controller, manager_programs_controller

manager_blueprint = Blueprint("manager", __name__)


@manager_blueprint.route('/manager', methods=["GET"])
def dashboard_view():
    return manager_controller.index(request)


# Manager-pationt Routes
@manager_blueprint.route('/pationt/pending', methods=["GET"])
def get_pending_pationt_view():
    return manager_pationt_controller.get_pending_pationt(request)


@manager_blueprint.route('/approve/pationt/', methods=["POST"])
def approve_pationt():
    return manager_pationt_controller.approve_pationt_registration(request)


@manager_blueprint.route('/reject/pationt/', methods=["POST"])
def reject_pationt():
    return manager_pationt_controller.reject_pationt_registration(request)


@manager_blueprint.route('/tpationt/requests', methods=["GET"])
def get_pationt_requests():
    return manager_pationt_controller.get_pationt_requests_view(request)


@manager_blueprint.route('/pationt/requests/approve', methods=["POST"])
def approve_pationt_requests():
    return manager_pationt_controller.approve_pationt_request(request)


@manager_blueprint.route('/tpationt/requests/reject', methods=["POST"])
def reject_pationt_requests():
    return manager_pationt_controller.reject_pationt_request(request)


@manager_blueprint.route('/pationt/deactivate/all', methods=["GET"])
def get_deactivate_pationt_view():
    return manager_pationt_controller.get_deactivate_pationt(request)


@manager_blueprint.route('/pationt/deactivate', methods=["POST"])
def deactivate_pationt():
    return manager_pationt_controller.approve_pationt_deactivation(request)


@manager_blueprint.route('/pationt/reject/deactivate', methods=["POST"])
def reject_deactivate_pationt():
    return manager_pationt_controller.reject_pationt_deactivation(request)


@manager_blueprint.route('/pationt/account', methods=["GET"])
def get_pationt_accounts_view():
    return manager_pationt_controller.get_pationt_account(request)


@manager_blueprint.route('/pationt/account/details', methods=["GET"])
def get_pationt_accounts_details_view():
    return manager_pationt_controller.get_pationt_account_details(request)


@manager_blueprint.route('/pationt/approve/modifications', methods=["POST"])
def accept_pationt_modification():
    return manager_pationt_controller.accept_pationt_modifications(request)


@manager_blueprint.route('/pationt/reject/modifications', methods=["POST"])
def reject_pationt_modification():
    return manager_pationt_controller.reject_pationt_modifications(request)


# Manager-dector Routes


@manager_blueprint.route('/dector/pending', methods=["GET"])
def get_pending_dector_view():
    return manager_dector_controller.get_pending_dector(request)


@manager_blueprint.route('/approve/dector', methods=["POST"])
def approve_dector():
    return manager_dector_controller.approve_dectors_registration(request)


@manager_blueprint.route('/reject/dector', methods=["POST"])
def reject_dector():
    return manager_dector_controller.reject_dectors_registration(request)


@manager_blueprint.route('/dectors/account', methods=["GET"])
def get_dectors_accounts_view():
    return manager_dector_controller.get_dector_account(request)


@manager_blueprint.route('/dectors/account/details', methods=["GET"])
def get_dectors_accounts_details_view():
    return manager_dector_controller.get_dector_account_details(request)


@manager_blueprint.route('/dectors/approve/modifications', methods=["POST"])
def accept_dector_modification():
    return manager_dector_controller.accept_dector_modifications(request)


@manager_blueprint.route('/dectors/account/details', methods=["POST"])
def reject_dector_modification():
    return manager_dector_controller.reject_dector_modifications(request)


@manager_blueprint.route('/dectors/deactivate/all', methods=["GET"])
def get_deactivate_dectors_view():
    return manager_dector_controller.get_deactivate_dectors(request)


@manager_blueprint.route('/dector/deactivate', methods=["POST"])
def deactivate_dector():
    return manager_dector_controller.approve_dector_deactivation(request)


@manager_blueprint.route('/dector/reject/deactivate', methods=["POST"])
def reject_deactivate_dector():
    return manager_dector_controller.reject_dector_deactivation(request)

# Progam Routes

@manager_blueprint.route('/programs', methods=["GET"])
def get_all_programs_view():
    return manager_programs_controller.get_all_programs(request)


@manager_blueprint.route('/programs/create/form', methods=["GET"])
def get_add_program_view():
    return manager_programs_controller.get_add_program(request)


@manager_blueprint.route('/program/create', methods=["POST"])
def add_program():
    return manager_programs_controller.handle_add_program(request)


@manager_blueprint.route('/programs/edit', methods=["GET"])
def get_edit_program_view():
    return manager_programs_controller.get_edit_program(request)


@manager_blueprint.route('/programs/edit/save', methods=["POST"])
def edit_program():
    return manager_programs_controller.handle_edit_program(request)


@manager_blueprint.route('/program/delete', methods=["POST"])
def delete_program():
    return manager_programs_controller.handle_delete_program(request)

# Manager - Billing
@manager_blueprint.route('/billing', methods=["GET"])
def get_balance_sheet_view():
    return manager_controller.get_balance_sheet(request)



# Manager - Emailing
@manager_blueprint.route('/email/create', methods=["GET"])
def get_email_form():
    return manager_controller.get_email_form(request)


@manager_blueprint.route('/email/send', methods=["POST"])
def send_email():
    return manager_controller.send_email(request)



# Manager - System Log
@manager_blueprint.route('/systemlog', methods=["GET"])
def get_system_log():
    return manager_controller.get_system_log(request)

blueprints/auth_blueprint.py
from flask import Flask, Blueprint, render_template, url_for, redirect, request, flash
from controller import auth_controller

auth_blueprint = Blueprint("auth", __name__)

# to make sure nothing goes wrong
@auth_blueprint.route('/', methods=['GET'])
def home():
    return redirect(url_for('auth.login_view'))

# this is the route that returns the login form view
@auth_blueprint.route('/login', methods=['GET'])
def login_view():
    return auth_controller.login_view()


# this is the route that handles the login request
@auth_blueprint.route('/auth/login', methods=['POST'])
def login():
    return auth_controller.handle_login(request)


# this is the route that returns the signup form view
@auth_blueprint.route('/signup', methods=['GET'])
def signup_view():
    return auth_controller.signup_view(request)


# this is the route that handles the signup request
@auth_blueprint.route('/auth/signup', methods=['POST'])
def signup():
    classification = request.form['classification']
    if classification == 'trainee':
        return auth_controller.handle_trainee_signup(request)
    elif classification == 'advisor':
        return auth_controller.handle_advisor_signup(request)
    else:
        flash('Something is not right', 'error')
        return redirect(url_for('auth.login_view'))

# signout route
@auth_blueprint.route('/signout', methods=['GET'])
def signout():
    return auth_controller.signout(request)




templates/layouts/dector_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>{% block title %}{% endblock %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <!-- Favicons -->
    <link href="../../static/assets/img/favicon.png" rel="icon">
    <link href="../../static/assets/img/apple-touch-icon.png" rel="apple-touch-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="../../static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../../static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="../../static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="../../static/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="../../static/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="../../static/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="../../static/assets/vendor/simple-datatables/style.css" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="../../static/assets/css/style.css" rel="stylesheet">
</head>
<body>
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="#" class="logo d-flex align-items-center">
            <img src="../../static/assets/img/logo.png" alt="">
            <span class="d-none d-lg-block">TMS</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
        <form class="search-form d-flex align-items-center" method="POST" action="#">
            <input type="text" name="query" placeholder="Search" title="Enter search keyword">
            <button type="submit" title="Search"><i class="bi bi-search"></i></button>
        </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->
            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    <span class="badge bg-primary badge-number">4</span>
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        You have 4 new notifications
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-exclamation-circle text-warning"></i>
                        <div>
                            <h4>Lorem Ipsum</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>30 min. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li class="dropdown-footer">
                        <a href="#">Show all notifications</a>
                    </li>

                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->

            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-chat-left-text"></i>
                    <span class="badge bg-success badge-number">3</span>
                </a><!-- End Messages Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
                    <li class="dropdown-header">
                        You have 3 new messages
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="assets/img/messages-1.jpg" alt="" class="rounded-circle">
                            <div>
                                <h4>Maria Hudson</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>4 hrs. ago</p>
                            </div>
                        </a>
                    </li>


                    <li class="dropdown-footer">
                        <a href="#">Show all messages</a>
                    </li>

                </ul><!-- End Messages Dropdown Items -->

            </li><!-- End Messages Nav -->

            <li class="nav-item dropdown pe-3">
                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <img src="../../static/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">{{ advisor.username }}</span>
                </a><!-- End Profile Image Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>{{ advisor.username }}</h6>
                        <span>advisor</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{{url_for('auth.signout')}}">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Sign Out</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <a class="nav-link collapsed" href="{{ url_for("advisor.dashboard_view") }}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->
        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#trainees-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-people"></i><span>My Trainees</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="trainees-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{{ url_for("advisor.active_trainees") }}">
                        <i class="bi bi-circle"></i><span>Current Trainees</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Trainees Nav -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="{{ url_for('advisor.get_advisor_meetings_view') }}">
                <i class="bi bi-clock"></i>
                <span>Meetings</span>
            </a>
        </li>
    </ul>
</aside>
<!-- End Sidebar-->
<!-- ======= Main page content goes here ======= -->
{% block content %}
{% endblock %}
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
<!-- Vendor JS Files -->
<script src="../../static/assets/vendor/apexcharts/apexcharts.min.js"></script>
<script src="../../static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="../../static/assets/vendor/chart.js/chart.umd.js"></script>
<script src="../../static/assets/vendor/echarts/echarts.min.js"></script>
<script src="../../static/assets/vendor/quill/quill.min.js"></script>
<script src="../../static/assets/vendor/simple-datatables/simple-datatables.js"></script>
<script src="../../static/assets/vendor/tinymce/tinymce.min.js"></script>
<script src="../../static/assets/vendor/php-email-form/validate.js"></script>
<!-- Template Main JS File -->
<script src="../../static/assets/js/main.js"></script>
</body>
</html>

templates/layouts/manager_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %}{% endblock %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="../../static/assets/img/favicon.png" rel="icon">
    <link href="../../static/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="../../static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../../static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="../../static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="../../static/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="../../static/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="../../static/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="../../static/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="../../static/assets/css/style.css" rel="stylesheet">

</head>

<body>
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="#" class="logo d-flex align-items-center">
            <img src="../../static/assets/img/logo.png" alt="">
            <span class="d-none d-lg-block">TMS</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
        <form class="search-form d-flex align-items-center" method="POST" action="#">
            <input type="text" name="query" placeholder="Search" title="Enter search keyword">
            <button type="submit" title="Search"><i class="bi bi-search"></i></button>
        </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->
            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    <span class="badge bg-primary badge-number">4</span>
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        You have 4 new notifications
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-exclamation-circle text-warning"></i>
                        <div>
                            <h4>Lorem Ipsum</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>30 min. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li class="dropdown-footer">
                        <a href="#">Show all notifications</a>
                    </li>

                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->

            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-chat-left-text"></i>
                    <span class="badge bg-success badge-number">3</span>
                </a><!-- End Messages Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
                    <li class="dropdown-header">
                        You have 3 new messages
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="assets/img/messages-1.jpg" alt="" class="rounded-circle">
                            <div>
                                <h4>Maria Hudson</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>4 hrs. ago</p>
                            </div>
                        </a>
                    </li>


                    <li class="dropdown-footer">
                        <a href="#">Show all messages</a>
                    </li>

                </ul><!-- End Messages Dropdown Items -->

            </li><!-- End Messages Nav -->

            <li class="nav-item dropdown pe-3">
                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <img src="../../static/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">{{ manager.username }}</span>
                </a><!-- End Profile Image Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>{{ manager.username }}</h6>
                        <span>Manager</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="bi bi-gear"></i>
                            <span>Account Settings</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{{ url_for('auth.signout') }}">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Sign Out</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <a class="nav-link collapsed" href="{{ url_for('manager.dashboard_view') }}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#trainees-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-people"></i><span>Trainees</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="trainees-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{{ url_for('manager.get_pending_trainees_view') }}">
                        <i class="bi bi-circle"></i><span>Approve Trainee Registration</span>
                    </a>
                </li>

                <li>
                    <a href="{{ url_for('manager.get_training_requests') }}">
                        <i class="bi bi-circle"></i><span>Approve Training Requests</span>
                    </a>
                </li>

                <li>
                    <a href="{{ url_for('manager.get_trainees_accounts_view') }}">
                        <i class="bi bi-circle"></i><span>Approve Account Modification</span>
                    </a>
                </li>

                <li>
                    <a href="{{ url_for('manager.get_deactivate_trainees_view') }}">
                        <i class="bi bi-circle"></i> <span>Deactivate Account</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Trainees Nav -->


        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#advisors-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-people"></i><span>Advisors</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="advisors-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{{ url_for('manager.get_pending_advisors_view') }}">
                        <i class="bi bi-circle"></i><span>Approve Registration</span>
                    </a>
                </li>

                <li>
                    <a href="{{ url_for('manager.get_advisors_accounts_view') }}">
                        <i class="bi bi-circle"></i><span>Approve Account Modification</span>
                    </a>
                </li>

                <li>
                     <a href="{{ url_for('manager.get_deactivate_advisors_view') }}">
                         <i class="bi bi-circle"></i><span>Deactivate Account</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Advisors Nav -->

         <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#programs-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Training Programs</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="programs-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li class="nav-item">
                    <a  href="{{ url_for('manager.get_all_programs_view') }}">
                         <i class="bi bi-circle"></i><span>All programs</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('manager.get_add_program_view') }}">
                         <i class="bi bi-circle"></i><span>Add new</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Programs Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{{ url_for('manager.get_balance_sheet_view') }}">
                <i class="bi bi-bank"></i>
                <span>Balance Sheet</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{{ url_for('manager.get_email_form') }}">
                <i class="bi bi-envelope"></i>
                <span>Send an Email</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{{ url_for('manager.get_system_log') }}">
                <i class="bi bi-archive"></i>
                <span>System Log</span>                
            </a>
        </li>
    </ul>

</aside>
<!-- End Sidebar-->

<!-- ======= Flask Flashed Messages ======= -->
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul class="flash-messages">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endwith %}
<!-- ======= Main page content goes here ======= -->

{% block content %}
{% endblock %}

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="../../static/assets/vendor/apexcharts/apexcharts.min.js"></script>
<script src="../../static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="../../static/assets/vendor/chart.js/chart.umd.js"></script>
<script src="../../static/assets/vendor/echarts/echarts.min.js"></script>
<script src="../../static/assets/vendor/quill/quill.min.js"></script>
<script src="../../static/assets/vendor/simple-datatables/simple-datatables.js"></script>
<script src="../../static/assets/vendor/tinymce/tinymce.min.js"></script>
<script src="../../static/assets/vendor/php-email-form/validate.js"></script>

<!-- Template Main JS File -->
<script src="../../static/assets/js/main.js"></script>

</body>

</html>