blueprints/auth_blueprint.py
from flask import Flask, Blueprint, render_template, url_for, redirect, request, flash
from controller import auth_controller

auth_blueprint = Blueprint("auth", __name__)

# to make sure nothing goes wrong
@auth_blueprint.route('/', methods=['GET'])
def home():
    return redirect(url_for('auth.login_view'))

# this is the route that returns the login form view
@auth_blueprint.route('/login', methods=['GET'])
def login_view():
    return auth_controller.login_view()


# this is the route that handles the login request
@auth_blueprint.route('/auth/login', methods=['POST'])
def login():
    return auth_controller.handle_login(request)


# this is the route that returns the signup form view
@auth_blueprint.route('/signup', methods=['GET'])
def signup_view():
    return auth_controller.signup_view(request)


# this is the route that handles the signup request
@auth_blueprint.route('/auth/signup', methods=['POST'])
def signup():
    classification = request.form['classification']
    if classification == 'trainee':
        return auth_controller.handle_trainee_signup(request)
    elif classification == 'advisor':
        return auth_controller.handle_advisor_signup(request)
    else:
        flash('Something is not right', 'error')
        return redirect(url_for('auth.login_view'))

# signout route
@auth_blueprint.route('/signout', methods=['GET'])
def signout():
    return auth_controller.signout(request)




templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Login</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="../static/assets/img/favicon.png" rel="icon">
    <link href="../static/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="../static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="../static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="../static/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="../static/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="../static/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="../static/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="../static/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: NiceAdmin
    * Updated: Jan 09 2025 with Bootstrap v5.2.3
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>
<main>
    <div class="container">
        <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">                        
                        <div class="d-flex justify-content-center py-4">
                            {#                            TODO: index.html is supposed to take us somewhere#}                           
                            <a href="index.html" class="logo d-flex align-items-center w-auto">
                                <img src="../static/assets/img/logo.png" alt="">
                                <span class="d-none d-lg-block">Welcome</span>
                            </a>
                        </div><!-- End Logo -->
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="pt-4 pb-2">
                                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                                    <p class="text-center small">Enter your email & password to login</p>
                                </div>
                                <form class="row g-3 needs-validation" method="POST"
                                      action="{{ url_for('auth.login') }}">
                                    <div class="col-12">
                                        <label for="yourEmail" class="form-label">Email</label>
                                        <input type="email" name="email" class="form-control" id="yourEmail"
                                               required>
                                        <div class="invalid-feedback">Please enter your password!</div>
                                    </div>

                                    <div class="col-12">
                                        <label for="yourPassword" class="form-label">Password</label>
                                        <input type="password" name="password" class="form-control" id="yourPassword"
                                               required>
                                        <div class="invalid-feedback">Please enter your password!</div>
                                    </div>

                                    <div class="col-12">
                                        <button class="btn btn-primary w-100" type="submit">Login</button>
                                    </div>
                                    {% with messages = get_flashed_messages() %}
                                    {% if messages %}
                                        <ul class="flash-messages">
                                        {% for message in messages %}                                
                                        <div class="alert alert-danger bg-danger text-light border-0 alert-dismissible fade show" role="alert">
                                            {{message}}
                                            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
                                        </div>
                                        {% endfor %}
                                        </ul>
                                        
                                    {% endif %}
                                    {% endwith %}
                                    <div class="col-12">
                                        <p class="small mb-0">Don't have account?<br>
                                            <a href="{{ url_for('auth.signup_view', classification='pationt') }}">Create a
                                                Trainee account</a><br>
                                            <a href="{{ url_for('auth.signup_view', classification='advisor') }}">Create an
                                                Advisor account</a>
                                        </p>
                                    </div>
                                </form>

                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </section>

    </div>
</main><!-- End #main -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="../static/assets/vendor/apexcharts/apexcharts.min.js"></script>
<script src="../static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="../static/assets/vendor/chart.js/chart.umd.js"></script>
<script src="../static/assets/vendor/echarts/echarts.min.js"></script>
<script src="../static/assets/vendor/quill/quill.min.js"></script>
<script src="../static/assets/vendor/simple-datatables/simple-datatables.js"></script>
<script src="../static/assets/vendor/tinymce/tinymce.min.js"></script>
<script src="../static/assets/vendor/php-email-form/validate.js"></script>

<!-- Template Main JS File -->
<script src="../static/assets/js/main.js"></script>

</body>

</html>