blueprints/administrator_blueprint.py
from flask import Blueprint, request
from controller.manager import manager_trainee_controller, manager_controller, manager_advisor_controller, manager_programs_controller

manager_blueprint = Blueprint("manager", __name__)


@manager_blueprint.route('/manager', methods=["GET"])
def dashboard_view():
    return manager_controller.index(request)


# Manager-pationt Routes
@manager_blueprint.route('/pationt/pending', methods=["GET"])
def get_pending_pationt_view():
    return manager_pationt_controller.get_pending_pationt(request)


@manager_blueprint.route('/approve/pationt/', methods=["POST"])
def approve_pationt():
    return manager_pationt_controller.approve_pationt_registration(request)


@manager_blueprint.route('/reject/pationt/', methods=["POST"])
def reject_pationt():
    return manager_pationt_controller.reject_pationt_registration(request)


@manager_blueprint.route('/tpationt/requests', methods=["GET"])
def get_pationt_requests():
    return manager_pationt_controller.get_pationt_requests_view(request)


@manager_blueprint.route('/pationt/requests/approve', methods=["POST"])
def approve_pationt_requests():
    return manager_pationt_controller.approve_pationt_request(request)


@manager_blueprint.route('/tpationt/requests/reject', methods=["POST"])
def reject_pationt_requests():
    return manager_pationt_controller.reject_pationt_request(request)


@manager_blueprint.route('/pationt/deactivate/all', methods=["GET"])
def get_deactivate_pationt_view():
    return manager_pationt_controller.get_deactivate_pationt(request)


@manager_blueprint.route('/pationt/deactivate', methods=["POST"])
def deactivate_pationt():
    return manager_pationt_controller.approve_pationt_deactivation(request)


@manager_blueprint.route('/pationt/reject/deactivate', methods=["POST"])
def reject_deactivate_pationt():
    return manager_pationt_controller.reject_pationt_deactivation(request)


@manager_blueprint.route('/pationt/account', methods=["GET"])
def get_pationt_accounts_view():
    return manager_pationt_controller.get_pationt_account(request)


@manager_blueprint.route('/pationt/account/details', methods=["GET"])
def get_pationt_accounts_details_view():
    return manager_pationt_controller.get_pationt_account_details(request)


@manager_blueprint.route('/pationt/approve/modifications', methods=["POST"])
def accept_pationt_modification():
    return manager_pationt_controller.accept_pationt_modifications(request)


@manager_blueprint.route('/pationt/reject/modifications', methods=["POST"])
def reject_pationt_modification():
    return manager_pationt_controller.reject_pationt_modifications(request)


# Manager-dector Routes


@manager_blueprint.route('/dector/pending', methods=["GET"])
def get_pending_dector_view():
    return manager_dector_controller.get_pending_dector(request)


@manager_blueprint.route('/approve/dector', methods=["POST"])
def approve_dector():
    return manager_dector_controller.approve_dectors_registration(request)


@manager_blueprint.route('/reject/dector', methods=["POST"])
def reject_dector():
    return manager_dector_controller.reject_dectors_registration(request)


@manager_blueprint.route('/dectors/account', methods=["GET"])
def get_dectors_accounts_view():
    return manager_dector_controller.get_dector_account(request)


@manager_blueprint.route('/dectors/account/details', methods=["GET"])
def get_dectors_accounts_details_view():
    return manager_dector_controller.get_dector_account_details(request)


@manager_blueprint.route('/dectors/approve/modifications', methods=["POST"])
def accept_dector_modification():
    return manager_dector_controller.accept_dector_modifications(request)


@manager_blueprint.route('/dectors/account/details', methods=["POST"])
def reject_dector_modification():
    return manager_dector_controller.reject_dector_modifications(request)


@manager_blueprint.route('/dectors/deactivate/all', methods=["GET"])
def get_deactivate_dectors_view():
    return manager_dector_controller.get_deactivate_dectors(request)


@manager_blueprint.route('/dector/deactivate', methods=["POST"])
def deactivate_dector():
    return manager_dector_controller.approve_dector_deactivation(request)


@manager_blueprint.route('/dector/reject/deactivate', methods=["POST"])
def reject_deactivate_dector():
    return manager_dector_controller.reject_dector_deactivation(request)

# Progam Routes

@manager_blueprint.route('/programs', methods=["GET"])
def get_all_programs_view():
    return manager_programs_controller.get_all_programs(request)


@manager_blueprint.route('/programs/create/form', methods=["GET"])
def get_add_program_view():
    return manager_programs_controller.get_add_program(request)


@manager_blueprint.route('/program/create', methods=["POST"])
def add_program():
    return manager_programs_controller.handle_add_program(request)


@manager_blueprint.route('/programs/edit', methods=["GET"])
def get_edit_program_view():
    return manager_programs_controller.get_edit_program(request)


@manager_blueprint.route('/programs/edit/save', methods=["POST"])
def edit_program():
    return manager_programs_controller.handle_edit_program(request)


@manager_blueprint.route('/program/delete', methods=["POST"])
def delete_program():
    return manager_programs_controller.handle_delete_program(request)

# Manager - Billing
@manager_blueprint.route('/billing', methods=["GET"])
def get_balance_sheet_view():
    return manager_controller.get_balance_sheet(request)



# Manager - Emailing
@manager_blueprint.route('/email/create', methods=["GET"])
def get_email_form():
    return manager_controller.get_email_form(request)


@manager_blueprint.route('/email/send', methods=["POST"])
def send_email():
    return manager_controller.send_email(request)



# Manager - System Log
@manager_blueprint.route('/systemlog', methods=["GET"])
def get_system_log():
    return manager_controller.get_system_log(request)

templates/manager/hms-program/add_program.html
{% extends "layouts/manager_base.html" %}

{% block title %} Add Program {% endblock %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Add New Training Program</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Manager</a></li>
                    <li class="breadcrumb-item"><a href="{{ url_for('manager.get_all_programs_view') }}">Training
                        Programs</a></li>
                    <li class="breadcrumb-item"><a href="#">Create</a></li>
                </ol>
            </nav>
        </div><!-- End Page Title -->
        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Training Program Details</h5>
                            <!-- Horizontal Form -->
                            <form action="{{url_for('manager.add_program')}}" method="post">
                                <div class="row mb-3">
                                    <label for="programName" class="col-sm-2 col-form-label">Program Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="programName" name="programName">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="description" class="col-sm-2 col-form-label">Program
                                        Description</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="description"
                                               name="description">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="area" class="col-sm-2 col-form-label">Program Area</label>
                                    <div class="col-sm-10">
                                        <select id="area" class="col-sm-10 form-select" name="area">
                                            <option selected value="">Choose...</option>
                                            {% for area in areas %}
                                                <option value="{{ area }}">{{ area }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="fees" class="col-sm-2 col-form-label">Program
                                        Fees</label>
                                    <div class="col-sm-10">
                                        <input type="number" class="form-control" id="fees"
                                               name="fees">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="start" class="col-sm-2 col-form-label">Program
                                        Start Date</label>
                                    <div class="col-sm-10">
                                        <input type="date" class="form-control" id="start"
                                               name="start">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="end" class="col-sm-2 col-form-label">Program
                                        End Date</label>
                                    <div class="col-sm-10">
                                        <input type="date" class="form-control" id="end"
                                               name="end">
                                    </div>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Add</button>
                                    <button type="reset" class="btn btn-secondary">Reset</button>
                                </div>
                            </form><!-- End Horizontal Form -->
                        </div>
                    </div>
                </div>
            </div>

        </section>

    </main><!-- End #main -->
{% endblock %}



templates/manager/hms-program/all_programs.html
{% extends "layouts/manager_base.html" %}

{% block title %} Training Programs {% endblock %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Training Programs</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Manager</a></li>
                    <li class="breadcrumb-item"><a href="{{ url_for('manager.get_all_programs_view') }}">Training
                        Programs</a></li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    {% with messages = get_flashed_messages(with_categories=True) %}
                    {% if messages %}
                        <ul class="flash-messages">
                        {% for category, message in messages %} 
                            {% if category == 'error' %}
                            <div class="alert alert-danger bg-danger text-light border-0 alert-dismissible fade show" role="alert">
                                {{message}}
                                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                            {% elif category == 'success' %}
                            <div class="alert alert-success bg-success text-light border-0 alert-dismissible fade show" role="alert">
                                {{message}}
                                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                            {% endif %}
                        {% endfor %}
                        </ul>                                        
                    {% endif %}
                    {% endwith %}
                    <div class="card">
                        <div class="card-body">
                            <!-- Table with stripped rows -->
                            <table class="table datatable">
                                <thead>
                                <tr>
                                    <th scope="col">Id</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Description</th>
                                    <th scope="col">Area</th>
                                    <th scope="col">Fees</th>
                                    <th scope="col">Start Date</th>
                                    <th scope="col">End Date</th>
                                    <th scope="col">-</th>
                                    <th scope="col">-</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for program in programs %}
                                    <tr>
                                        <th scope="row">{{ program[0] }}</th>
                                        <td>{{ program[1] }}</td>
                                        <td>{{ program[2] }}</td>
                                        <td>{{ program[3] }}</td>
                                        <td>{{ program[4] }}</td>
                                        <td>{{ program[5] }}</td>
                                        <td>{{ program[6] }}</td>
                                        <td>
                                            <a href="{{ url_for('manager.get_edit_program_view', id=program[0]) }}">Edit</a>
                                        </td>
                                        <td>
                                            <form method="POST" action="{{ url_for('manager.delete_program') }}">
                                                <input type="hidden" name="programID" value="{{program[0]}}">
                                                <button class="btn btn-danger" data-bs-toggle="modal"
                                                        data-bs-target="#verticalycentered" type="submit">Delete
                                                </button>
                                            </form></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>                            
                        </div>
                    </div>
                </div>
            </div>

        </section>

    </main><!-- End #main -->
{% endblock %}



templates/manager/hms-program/update_program.html
{% extends "layouts/manager_base.html" %}

{% block title %} Edit Program {% endblock %}
{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Edit Training Program</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Manager</a></li>
                    <li class="breadcrumb-item"><a href="{{ url_for('manager.get_all_programs_view') }}">Training
                        Programs</a></li>
                    <li class="breadcrumb-item"><a href="#">Edit</a></li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Training Program Details</h5>
                            <!-- Horizontal Form -->
                            <form action="{{url_for('manager.edit_program')}}" method="POST">
                                <div class="row mb-3">
                                    <label for="programName" class="col-sm-2 col-form-label">Program Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="programName" name="programName"
                                               value="{{ program[1] }}">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="description" class="col-sm-2 col-form-label">Program
                                        Description</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="description"
                                               name="description" value="{{ program[2] }}">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="area" class="col-sm-2 col-form-label">Program Area</label>
                                    <div class="col-sm-10">
                                        <select id="area" class="col-sm-10 form-select" name="area">
                                            <option selected value="">Choose...</option>
                                            {% for area in areas %}
                                                <option {% if area == program[3] %} selected = selected{% endif %}value="{{ area }}">{{ area }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>


                                <div class="row mb-3">
                                    <label for="fees" class="col-sm-2 col-form-label">Program
                                        Fees</label>
                                    <div class="col-sm-10">
                                        <input type="number" class="form-control" id="fees"
                                               name="fees" value="{{ program[4] }}">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="start" class="col-sm-2 col-form-label">Program
                                        Start Date</label>
                                    <div class="col-sm-10">
                                        <input type="date" class="form-control" id="start"
                                               name="start" required value="{{ program[5] }}">
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="end" class="col-sm-2 col-form-label">Program
                                        End Date</label>
                                    <div class="col-sm-10">
                                        <input type="date" required class="form-control" id="end"
                                               name="end" value="{{ program[6] }}">
                                    </div>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Save Edit</button>
                                    <input type="hidden" value="{{program[0]}}" name="programID">
                                    <button type="reset" class="btn btn-secondary">Reset</button>
                                </div>
                            </form><!-- End Horizontal Form -->
                        </div>
                    </div>
                </div>
            </div>

        </section>

    </main><!-- End #main -->
{% endblock %}

